d <- read.csv("veri.csv", na.strings=c("", "NA"))
stopifnot(identical(names(d),c("grup","puan")), !anyNA(d),all(d$grup %in% 1:2),all(is.finite(d$puan)))
x<-d$puan[d$grup==1];y<-d$puan[d$grup==2];stopifnot(length(x)>1,length(y)>1)
w<-wilcox.test(x,y,alternative="two.sided",exact=FALSE,correct=FALSE)
u<-unname(w$statistic);nn<-length(x)*length(y)
s<-c(n_1=length(x),n_2=length(y),medyan_1=median(x),medyan_2=median(y),U_1=u,U_min=min(u,nn-u),p_asimptotik=w$p.value,ustunluk=u/nn,sira_biserial=2*u/nn-1)
esli<-read.csv("esli.csv");uc<-read.csv("uc-grup.csv")
stopifnot(identical(names(esli),c("fark","sifir")),!anyNA(esli),all(esli$sifir==0),all(is.finite(esli$fark)),any(esli$fark!=0))
f<-esli$fark;w<-wilcox.test(f,alternative="two.sided",exact=FALSE,correct=FALSE)
nz<-sum(f!=0);wmin<-min(unname(w$statistic),nz*(nz+1)/2-unname(w$statistic))
sg<-binom.test(sum(f>0),nz,p=.5)
stopifnot(identical(names(uc),c("grup","puan")),!anyNA(uc),all(uc$grup %in% 1:3),all(is.finite(uc$puan)),all(table(factor(uc$grup,levels=1:3))>1))
kw<-kruskal.test(puan~factor(grup),data=uc)
s<-c(s,wilcoxon_W_min=wmin,wilcoxon_p_asimptotik=w$p.value,isaret_p_kesin=sg$p.value,kruskal_H=unname(kw$statistic),kruskal_p=kw$p.value,epsilon_kare=(unname(kw$statistic)-2)/(nrow(uc)-3))
out<-data.frame(olcut=names(s),deger=as.numeric(s))
print(out,row.names=FALSE);write.csv(out,"sonuclar-r.csv",row.names=FALSE)
if("--check" %in% commandArgs(trailingOnly=TRUE)){
 ref<-read.csv("beklenen-sonuclar.csv")
 stopifnot(identical(out$olcut,ref$olcut),all(abs(out$deger-ref$deger)<=1e-10+1e-8*abs(ref$deger)))
 cat("KONTROL BASARILI\n")
}
sessionInfo()
